AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: false

Bundler/OrderedGems:
  Enabled: false

Style/SingleLineMethods:
  Enabled: true
  AllowIfMethodIsEmpty: false
