language: ruby
env:
    - COVERAGE=true
before_install:
  - gem install bundler
script: bundle exec rspec spec
rvm:
  - 2.1
  - 2.2
  - 2.3.0
  - rbx-2
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
