require "errbit_plugin/version"
require "errbit_plugin/register_plugin"
require "errbit_plugin/issue_tracker"
require "errbit_plugin/validate_issue_tracker"
require "errbit_plugin/issue_trackers/none"
